# [unstable]
# build-std         =["alloc", "core", "panic_abort", "proc_macro", "std"]
# build-std-features=["panic_immediate_abort"]

[build]
rustflags=[
"--cfg=has_std",
"-C", "panic=abort",
"-C", "link-arg=/LIMIT:10240"
]

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags=["-C", "target-feature=+crt-static","-C", "target-cpu=generic"]
