import { Palette, Button,ListView, VerticalBox } from "std-widgets.slint";

export global PercentageInput {
    in-out property <string> name;
    in-out property <string> classname;
}

export component PercentageWindow inherits Window {
    width: 300px;
    height: 200px;
    title: "Percentage Input";
    icon: @image-url("../icons/app-icon.png");
    always-on-top: true;
    callback submit(string);
    callback cancel();
    VerticalLayout {
        padding: 20px;
        spacing: 20px;
        Text {
            font-italic: true;
            font-size: 20px;
            font-weight: 500;
            horizontal-alignment: TextHorizontalAlignment.center;
            text: PercentageInput.name;
            vertical-alignment: center;
        }

        HorizontalLayout {
            spacing: 10px;
            Text {
                font-size: 14px;
                font-weight: 500;
                text: "Enter percentage:";
                vertical-alignment: center;
            }

            Rectangle {
                background: #161515;
                height: 20px;
                y: 2.5px;
                width: 100px;
                input := TextInput {
                    vertical-alignment: TextVerticalAlignment.center;
                    width: 90px;
                    color: #fff;
                    height: 20px;
                    text: "95";
                    horizontal-alignment: TextHorizontalAlignment.right;
                    input-type: InputType.decimal;
                    changed text => {
                        if self.text.to-float() > 100 {
                            self.text = 100;
                        } else if self.text.to-float() < 1 {
                            self.text = 1;
                        }
                    }
                    key-pressed(event) => {
                        if (event.text == Key.UpArrow) {
                            self.text = self.text.to-float() + 1;
                            accept
                        }
                        if (event.text == Key.DownArrow) {
                            self.text = self.text.to-float() - 1;
                            accept
                        }
                        reject
                    }
                }
            }
        }

        VerticalLayout {
            HorizontalLayout {
                Text {
                    font-size: 13px;
                    text: "Class:";
                }

                Text {
                    text: PercentageInput.classname;
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: 20px;
            Button {
                text: "Submit";
                width: 80px;
                height: 30px;
                clicked => {
                    root.submit(input.text);
                }
            }

            Button {
                text: "Cancel";
                width: 80px;
                height: 30px;
                clicked => {
                    root.cancel();
                }
            }
        }
    }
}
